package com.bhoopesh.service;
import java.util.Scanner;

import com.bhoopesh.banking.InternetBanking;

public class IndianBank implements InternetBanking{

	
	private int bankBalance = 1000;
	private int amount;
	
	Scanner sc = new Scanner(System.in);
	
	@Override
	public void deposit() {
		//ask the amount that user wants to deposit
		System.out.println("Enter the amount you want to deposit");
		amount = sc.nextInt();
		
		if(amount > 0) {
			System.out.println("amount " + amount + " deposited successfully");
			bankBalance = bankBalance + amount;
			System.out.println("Updated bank balance is : " +  bankBalance);
		}
		else
			System.out.println("Enter the valid amount greater than 0");
	}

	@Override
	public void withdrawal() {
		System.out.println("Enter the amount you want to withdrawal");
		amount = sc.nextInt();
		
		if(amount <= 0)
			System.out.println("Enter the valid amount greater than 0");
		
		else if(amount > bankBalance)
			System.out.println("Insufficient balance");
		else {
			System.out.println("amount " + amount + " withdrawal successfully");
			bankBalance = bankBalance - amount;
			System.out.println("Updated bank balance is : " +  bankBalance);
		}
			

		
	}

	@Override
	public void checkBalance() {
		
		System.out.println("Current bank balance is : " + bankBalance);
	}

	@Override
	public void transfer() {
		
		//generate OTP
		OTPGenerator otpG = new OTPGenerator();
		System.out.println("Enter the OTP");
		int otpGenerated = otpG.generateOTP(); // otp generated by system
		System.out.println(otpGenerated);
		
		int otpUser = sc.nextInt(); // otp entered by user
		
		if(otpGenerated == otpUser) {
			System.out.println("OTP verification sucessfull");
			
			System.out.println("Enter the amount you want to transfer");
			amount = sc.nextInt();

			
			if(amount <= 0)
				System.out.println("Enter the valid amount greater than 0");
			
			else if(amount > bankBalance)
				System.out.println("Insufficient balance");
			else {
				System.out.println("Enter the bank account number to which you want to transfer");
				int bankAccountNo = sc.nextInt();
				
				System.out.println("amount " + amount + " transferred successfully to bankAccount " + bankAccountNo);
				bankBalance = bankBalance - amount;
				System.out.println("Updated bank balance is : " +  bankBalance);
			}
			
		}
		else
			System.out.println("invalid otp, please try again");
		
	}
	
	
	public void logout() {
		sc.close();
	}
	
}
